name: Manual Approval Workflow
run-name: Update release version to ${{ github.event.inputs.version }}

on:
  workflow_dispatch: # Позволяет запускать workflow вручную через UI GitHub
    inputs:
      version:
        description: 'Version to be updated in pubspec.yaml'
        required: true
        default: '0.0.0+1'

jobs:
  check-draft:
    runs-on: ubuntu-latest
    steps:
      - name: Check if PR is a draft
        id: check_draft
        run: |
          echo "PR is draft: ${{ github.event.pull_request.draft }}"

      - name: Conditional step based on draft status
        if: ${{ github.event.pull_request.draft == true }}
        run: echo "This pull request is a draft."

      - name: Another conditional step based on draft status
        if: ${{ github.event.pull_request.draft == false }}
        run: echo "This pull request is not a draft."

  display-inputs:
    runs-on: ubuntu-latest
    steps:
      - name: Display inputs for approval
        run: |
          echo "Version to be updated: ${{ github.event.inputs.version }}"

#  request-approval:
  request-approval:
    runs-on: ubuntu-latest
    needs: display-inputs
    environment:
      name: ci cd workflow
      # Требует одобрения в этом environment
    steps:
      - name: Approval step
        run: echo "This step requires approval"

  after-approval:
    runs-on: ubuntu-latest
    needs: request-approval
    steps:
      - name: Do something after approval
        run: echo "Approved and proceeding with the workflow"
