name: Manual Approval Workflow
run-name: Update release version to ${{ github.event.inputs.version }}

on:
  workflow_dispatch: # Позволяет запускать workflow вручную через UI GitHub
    inputs:
      version:
        description: 'Version to be updated in pubspec.yaml'
        required: true
        default: '0.0.0+1'

jobs:
  check_draft:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Get PR context
        id: get_context
        run: |
          echo "${{ toJson(github.event) }}" > event_context.json
          cat event_context.json

      - name: Check if PR is in draft state
        id: check_draft
        run: |
          is_draft=$(jq .pull_request.draft event_context.json)
          echo "Pull Request Draft State: $is_draft"
          echo "::set-output name=is_draft::$is_draft"

      - name: Take action based on draft state
        run: |
          if [ "${{ steps.check_draft.outputs.is_draft }}" = "true" ]; then
            echo "Skipping certain steps because PR is a draft."
            # Add actions you want to skip or modify if the PR is a draft
          else
            echo "Proceeding with the full workflow."
            # Add your normal actions here
          fi

  display-inputs:
    runs-on: ubuntu-latest
    steps:
      - name: Display inputs for approval
        run: |
          echo "Version to be updated: ${{ github.event.inputs.version }}"

#  request-approval:
  request-approval:
    runs-on: ubuntu-latest
    needs: display-inputs
    environment:
      name: ci cd workflow
      # Требует одобрения в этом environment
    steps:
      - name: Approval step
        run: echo "This step requires approval"

  after-approval:
    runs-on: ubuntu-latest
    needs: request-approval
    steps:
      - name: Do something after approval
        run: echo "Approved and proceeding with the workflow"
