name: Manual Approval Workflow

on:
  workflow_dispatch: # Позволяет запускать workflow вручную через UI GitHub

jobs:
  request-approval:
    runs-on: ubuntu-latest
    environment:
      name: ci cd workflow
      # Требует одобрения в этом environment
    steps:
      - name: Approval step
        run: echo "This step requires approval"

  after-approval:
    runs-on: ubuntu-latest
    needs: request-approval
    steps:
      - name: Do something after approval
        run: echo "Approved and proceeding with the workflow"
