name: Manual Approval Workflow

run-name: Update release version to ${{ github.event.inputs.version }}

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to be updated in pubspec.yaml'
        required: true
        default: '0.0.0+1'

jobs:
  display-inputs:
    runs-on: ubuntu-latest

    steps:
      - name: Display inputs for approval
        run: |
          echo "Version to be updated: ${{ github.event.inputs.version }}"

      - name: Extract version from build_constants.gradle.kts
        run: |
          EXTRACTED_VERSION=$(grep 'extra\["library_version_name"\]' Imperva-Development/build_constants.gradle.kts | sed 's/.*extra\["library_version_name"\] = "\(.*\)".*/\1/')
          echo "last_version=$EXTRACTED_VERSION" >> $GITHUB_ENV

#        - name: Display extracted version
#          run: echo "Extracted version is ${{ env.extracted_version }}"

  #  request-approval:
  request-approval:
    runs-on: ubuntu-latest
    needs: display-inputs
    environment:
      name: ci cd workflow
    steps:
      - name: Display inputs for approval
        run: echo "This is request-approval job"

