name: Manual Approval Workflow
run-name: Update release version to ${{ github.event.inputs.version }}

on:
  workflow_dispatch: # Позволяет запускать workflow вручную через UI GitHub
    inputs:
      version:
        description: 'Version to be updated in pubspec.yaml'
        required: true
        default: '0.0.0+1'

jobs:
  check-draft:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Check if PR is in draft state
        id: check-draft
        run: |
          PR_DRAFT=$(jq '.pull_request.draft' < "${GITHUB_EVENT_PATH}")
          echo "PR draft state: $PR_DRAFT"
          echo "::set-output name=is_draft::$PR_DRAFT"

      - name: Take action based on draft state
        run: |
          if [[ "${{ steps.check-draft.outputs.is_draft }}" == "true" ]]; then
            echo "Skipping further steps because this is a draft pull request."
          else
            echo "Proceeding with further steps."
            # Add your other steps here
          fi

  display-inputs:
    runs-on: ubuntu-latest
    steps:
      - name: Display inputs for approval
        run: |
          echo "Version to be updated: ${{ github.event.inputs.version }}"

#  request-approval:
  request-approval:
    runs-on: ubuntu-latest
    needs: display-inputs
    environment:
      name: ci cd workflow
      # Требует одобрения в этом environment
    steps:
      - name: Approval step
        run: echo "This step requires approval"

  after-approval:
    runs-on: ubuntu-latest
    needs: request-approval
    steps:
      - name: Do something after approval
        run: echo "Approved and proceeding with the workflow"
