name: "Manual release pipeline"
run-name: Update release version to ${{ github.event.inputs.version }}
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'New version'
        required: true
        default: '0.0.0+1'

jobs:
  display-inputs:
    runs-on: ubuntu-latest

    steps:
      - name: Display inputs for approval
        run: |
          echo "Version to be updated: ${{ github.event.inputs.version }}"

#  #  request-approval:
#  request-approval:
#    runs-on: ubuntu-latest
#    needs: display-inputs
#    environment:
#      name: ci cd workflow
#    steps:
#      - name: Display inputs for approval
#        run: echo "This is request-approval job"



  release-new-version:
    name: Release new version
    needs: update-library-version
    uses: ./.github/workflow/release_pipeline.yml@ci_cd_test_2
    with:
      version: "1.1.1"
#      version: ${{ github.event.inputs.version }}
