name: Print GitHub Event JSON on Pull Request Events

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

jobs:
  print-event-json:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Print GitHub Event JSON
        run: echo "${{ toJson(github.event) }}"

