name: Manual Approval Workflow

on:
  pull_request:
    types: [ opened, synchronize, reopened, ready_for_review ]

jobs:
  pull-request-work:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@4

      - name: Print GitHub Event JSON
        run: echo '${{ toJson(github.event) }}'